version: "3.4"

services:
  node:
    container_name: node
    image: node:20
    working_dir: /var/www/html/app/
    user: node
    env_file: .env
    volumes:
      - ./:/var/www/html/app/
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: sh -c "npm i && npm run dev"
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: nodejs
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
     - .env
    ports:
      - 5555:5555
volumes:
  db_data:
